"""The generated web module must match its sources.

`scripts/gen-samples.py` renders `fixtures/samples/*.json` into
`apps/web/lib/generated-samples.ts`, because a serverless function cannot read a path it did
not trace at build time. A generated file with no drift gate is a file that silently rots:
someone edits the JSON, forgets to regenerate, and the web app keeps showing old recordings
while the CLI shows new ones — two surfaces disagreeing about the product's own data.

This is that gate.
"""

from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
from pathlib import Path
from types import ModuleType

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
SAMPLES = REPO_ROOT / "fixtures" / "samples"
WEB_MODULE = REPO_ROOT / "apps" / "web" / "lib" / "generated-samples.ts"
GENERATOR = REPO_ROOT / "scripts" / "gen-samples.py"


def load_generator() -> ModuleType:
    spec = importlib.util.spec_from_file_location("gen_samples", GENERATOR)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def rendered_module() -> str:
    """Render the module the generator would produce, without touching the working tree.

    Mirrors `scripts/gen-samples.py`, including the prettier pass: the generator formats its own
    output, so the committed bytes and the generated bytes are the same bytes.
    """
    generator = load_generator()
    sources = sorted(SAMPLES.glob("*.json"))
    blocks: list[str] = [generator.HEADER, ""]
    exported: list[str] = []

    for source in sources:
        payload = json.loads(source.read_text(encoding="utf-8"))
        name = source.stem.replace("-", "_").upper()
        blocks.append(f"export const {name}_TRACE = {generator.typescript_literal(payload)} as const")
        blocks.append("")
        exported.append(name)

    blocks.append("/** Every bundled recording, keyed by the id used in the compare form. */")
    blocks.append("export const SAMPLE_TRACES = {")
    for name in exported:
        blocks.append(f"  {name.lower()}: {name}_TRACE,")
    blocks.append("} as const")
    blocks.append("")
    blocks.append("export type SampleId = keyof typeof SAMPLE_TRACES")
    blocks.append("")
    blocks.append("export const SAMPLE_IDS = Object.keys(SAMPLE_TRACES) as readonly SampleId[]")
    blocks.append("")
    return _prettier("\n".join(blocks))


def _prettier(source: str) -> str:
    """Format the same way the generator does, so the comparison is byte-exact.

    prettier is invoked through `node` on its JS entry point rather than through `npx`, because
    `npx` is a `.cmd` shim on Windows and `subprocess` cannot exec one without a shell.
    """
    node = shutil.which("node")
    cli = REPO_ROOT / "node_modules" / "prettier" / "bin" / "prettier.cjs"
    if node is None or not cli.exists():  # pragma: no cover - only without a JS toolchain
        raise AssertionError(
            "prettier is unavailable, so the generated module cannot be verified. "
            "Run npm install first."
        )
    result = subprocess.run(
        [node, str(cli), "--parser", "typescript"],
        input=source,
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:  # pragma: no cover - only when prettier fails to run
        raise AssertionError(f"prettier failed: {result.stderr}")
    return result.stdout


def test_the_samples_exist() -> None:
    assert sorted(path.name for path in SAMPLES.glob("*.json")) == ["after.json", "before.json"]


def test_the_generated_module_is_current() -> None:
    assert WEB_MODULE.exists(), f"{WEB_MODULE} is missing; run python scripts/gen-samples.py"
    assert WEB_MODULE.read_text(encoding="utf-8") == rendered_module(), (
        "apps/web/lib/generated-samples.ts is stale. "
        "Run: python scripts/gen-samples.py"
    )


def test_the_containers_are_current() -> None:
    """The `.fld` files the CLI reads must match the JSON too."""
    from flame_diff.columns import encode
    from flame_diff.model import parse_trace

    for source in sorted(SAMPLES.glob("*.json")):
        container = source.with_suffix(".fld")
        assert container.exists(), f"{container} is missing; run python scripts/gen-samples.py"
        trace = parse_trace(json.loads(source.read_text(encoding="utf-8")))
        assert container.read_text(encoding="utf-8") == encode(trace), (
            f"{container.name} is stale. Run: python scripts/gen-samples.py"
        )


def test_the_samples_exercise_the_report() -> None:
    """The bundled recordings must actually demonstrate the product, not two empty traces."""
    from flame_diff.api import analyse

    base = json.loads((SAMPLES / "before.json").read_text(encoding="utf-8"))
    head = json.loads((SAMPLES / "after.json").read_text(encoding="utf-8"))
    report = analyse("diff", {"base": base, "head": head})

    stats = report["stats"]
    assert stats["added"] >= 1, "the sample pair should demonstrate an added span"
    assert stats["duration_regressed"] >= 1, "the sample pair should demonstrate a regression"
    assert stats["renamed"] >= 1, "the sample pair should demonstrate a rename"
    assert report["roundtrip"]["lossless"] is True